2019-08-15 22:53:56,413 ERROR: Exception on /search [GET] [in /home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/di/MyProjects/flask_projects/microblog/app/main/routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/di/MyProjects/flask_projects/microblog/app/models.py", line 22, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/di/MyProjects/flask_projects/microblog/app/search.py", line 26, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/client/__init__.py", line 852, in search
    "GET", _make_path(index, doc_type, "_search"), params=params, body=body
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/transport.py", line 353, in perform_request
    timeout=timeout,
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/connection/http_urllib3.py", line 246, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/connection/base.py", line 168, in _raise_error
    status_code, error_message, additional_info
elasticsearch6.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]')
2019-08-15 22:53:58,371 ERROR: Exception on /search [GET] [in /home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/di/MyProjects/flask_projects/microblog/app/main/routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/di/MyProjects/flask_projects/microblog/app/models.py", line 22, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/di/MyProjects/flask_projects/microblog/app/search.py", line 26, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/client/__init__.py", line 852, in search
    "GET", _make_path(index, doc_type, "_search"), params=params, body=body
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/transport.py", line 353, in perform_request
    timeout=timeout,
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/connection/http_urllib3.py", line 246, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/connection/base.py", line 168, in _raise_error
    status_code, error_message, additional_info
elasticsearch6.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]')
2019-08-15 22:55:14,883 INFO: Microblog startup [in /home/di/MyProjects/flask_projects/microblog/app/__init__.py:79]
2019-08-15 22:56:08,400 INFO: Microblog startup [in /home/di/MyProjects/flask_projects/microblog/app/__init__.py:79]
2019-08-15 22:57:26,616 INFO: Microblog startup [in /home/di/MyProjects/flask_projects/microblog/app/__init__.py:79]
2019-08-15 22:57:34,583 ERROR: Exception on /search [GET] [in /home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/di/MyProjects/flask_projects/microblog/app/main/routes.py", line 144, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/di/MyProjects/flask_projects/microblog/app/models.py", line 22, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/di/MyProjects/flask_projects/microblog/app/search.py", line 26, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/client/__init__.py", line 852, in search
    "GET", _make_path(index, doc_type, "_search"), params=params, body=body
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/transport.py", line 353, in perform_request
    timeout=timeout,
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/connection/http_urllib3.py", line 246, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/di/MyProjects/flask_projects/microblog/venv/lib/python3.7/site-packages/elasticsearch6/connection/base.py", line 168, in _raise_error
    status_code, error_message, additional_info
elasticsearch6.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]')
2019-08-15 23:22:53,918 INFO: Microblog startup [in /home/di/MyProjects/flask_projects/microblog/app/__init__.py:79]
